// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContexts))]
    partial class AppDbContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Model.Dto.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Member")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 4,
                            ImgUrl = "tyfujikn",
                            Member = true,
                            ProductName = "Maws300",
                            Value = 3000.0
                        },
                        new
                        {
                            ProductId = 1,
                            ImgUrl = "tyfujikn",
                            Member = true,
                            ProductName = "A1 Mapp Controller",
                            Value = 2536.0
                        },
                        new
                        {
                            ProductId = 2,
                            ImgUrl = "tyfujikn",
                            Member = false,
                            ProductName = "TMS CARD",
                            Value = 653.0
                        },
                        new
                        {
                            ProductId = 3,
                            ImgUrl = "tyfujikn",
                            Member = true,
                            ProductName = "A2 Mapp Controller",
                            Value = 81.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
